### PR TITLE
Update snapcraft.yaml

### PR DESCRIPTION
**Pull request by garbados**
Updates snapcraft.yaml to build latest CouchDB (3.2.2).

To be frank, I'm not entirely sure what I'm doing, but I tried to follow the hints left in the commit history. Please let me know if this is right!

### CODE REVIEW

**Comment by big-r81** [comment]
Hi, wasn’t Bintray switched off? Iirc the binaries should be at jfrog… Maybe @nickva can have a look…

**Comment by garbados** [comment]
Like I said, I don't really know what I'm doing. Bintray, jfrog -- these are things I don't know about. The big issue is that the snapcraft build is behind on a few security patches, and I'd like to get the latest release out so my CouchDB installation can automatically update.

**Comment by sklassen** [comment]
I use the snapcraft file here. https://github.com/sklassen/couchdb-pkg/tree/feature/jammy-3.2.2-sm91. 
This uses the new core22, the 3.2.2 source URL and SpiderMonkey91. 

But you'll need to build your own snapcraft file and then load it manually. 

```snap install ./couchdb_3.2.2_amd64.snap --dangerous```

**Comment by big-r81** [comment]
Closing via #119.

**Pull request closed without merging**
