### PR TITLE
Do not replace vm.args during update

### PR DESCRIPTION
**Pull request by jjrodrig**
## Overview
Do not replace vm.args config file when updating package. 

## Checklist

- [ ] Code is written and works correctly;
- [ ] Changes are covered by tests;
- [ ] Documentation reflects the changes;

### CODE REVIEW

**Comment by jjrodrig** [comment]
Thanks @wohali

**Comment by rnewson** [comment]
how will we deliver updated settings here in future upgrades?

**Comment by wohali** [comment]
@rnewson Same as local.ini now.

If it's not been changed by a user we'll overwrite it, if not we won't and put our file as `vm.args.rpmnew`

https://www.cl.cam.ac.uk/~jw35/docs/rpm_config.html

**Comment by rnewson** [comment]
ah super. in debian land there'd be a prompt to diff/merge, does that not happen in rpm land?

**Comment by wohali** [comment]
@rnewson No prompt, but a warning, which is OK I guess. Should look like:

```
warning: /opt/couchdb/etc/vm.args created as //opt/couchdb/etc/vm.args.rpmnew
```

Note: above is simulated, I haven't tried an upgrade from 2.3.1 to the new package yet.

**Comment by jjrodrig** [comment]
I've tested the current 3.0.0 package update in my centos 7 environment. This is the output:

```
  Updating  : couchdb-3.0.0-1.el7.x86_64                                                                                                                                                1/2
waring:/opt/couchdb/etc/local.ini created as /opt/couchdb/etc/local.ini.rpmnew
```

We should have the same waring for vm.args

**Pull request merged**
